### ISSUE TITLE
SELinuxがDisableになってる状態でVmの電源をつけるとエラーになる

### ISSUE THREAD

**Issue by yukamoja** [hibiki31/virty#10]
エラー文
error: unsupported configuration: Unable to find security driver for model selinux

**Comment by hibiki31** [comment]
Vmのsecurity deviceを削除すれば治るはずが、治らなかった。
SELinuxをpermmisiveにすれば動くらしいが、glustorの調子が悪くなった。
起動できてた時との違いはなんですか？

**Comment by yukamoja** [comment]
Glusterの不調ぐらいしか思い当たらないな。。

**Comment by hibiki31** [comment]
結果としては、**有効にしている状態で作ったVMは無効にすると動かなくなる。**
無効にした後に作ったVMは正常に起動できました。
SELinuxのポリシーを変更するのはVM作成する前に行ってください。
