### ISSUE TITLE
VMの削除ができない

### ISSUE THREAD

**Issue by yukamoja** [hibiki31/virty#11]
VMを削除するボタンを押したが一向に終わらないので、別タブを開いてTaskをみたら以下のエラー文が出ていた。
 
Requested operation is not valid: Refusing to undefine while domain managed save image exists

**Comment by hibiki31** [comment]
これはlibvirtに起因するエラーです。
例えばVMをサスペンドするとメモリ情報が保存されます。
そのような保存データが残っていると削除できません。

以下のコマンドで解決できます。
```
# virsh undefine --managed-save --domain domain-name
```
