### ISSUE TITLE
ログインしたユーザが所属しているVMだけを表示する機能が欲しい

### ISSUE THREAD

**Issue by yukamoja** [hibiki31/virty#12]
VMを作るときは1)VM作成者(ログインしてるユーザ), 2)VM作成者が所属しているグループのタグをつけ、VMの一覧取得時にはログインしているユーザが所属しているグループのタグがついたVMだけを表示するみたいなのを考えている。

作るグループは↓みたいなのを想定
- admin
- yamato
- seccamp

ユーザごとに権限が必要かもしれないが今は考えていない(面倒なので)

**Comment by hibiki31** [comment]
31eef6c932edd3cf063ede575c78ddcc139539be で実装
