### ISSUE TITLE
Next.js移行に伴うAPIの修正

### ISSUE THREAD

**Issue by taso0096** [hibiki31/virty#74]
新UI（Next.js）では、[OpenAPI Generator](https://openapi-generator.tech)を用いてAPIを叩いている。
それに伴い使用するAPIにはOpenAPIの定義を記述して欲しい。
また、今後必要な機能などがあればコメントに追加するので対応して欲しい。

**Comment by taso0096** [comment]
`/api/networks/:uuid`で存在しないuuidのときに404を返して欲しい。
多分今はネットワークを取得できていないのにオブジェクトにアクセスしているせいで500エラーになってる。

**Comment by taso0096** [comment]
Userモデルの定義がされてなさそう（型が`any`になってる）

**Comment by taso0096** [comment]
UUIDを指定して特定のタスク情報を取得するAPIが欲しい

**Comment by taso0096** [comment]
返ってくるユーザデータにパスワードが含まれているので消した方がいい

**Comment by hibiki31** [comment]
VMの電源についてもバグ修正を行う
